[package]
name = "loremaster"
description = "Tools to help Loremasters running The One Ring 2E"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
spin-sdk = "3.0.1"
strum = { version = "0.26.3", features = ["derive"] }

[lints]
workspace = true

[workspace]
resolver = "2"

[workspace.package]
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
categories = ["games"]
edition = "2021"
keywords = ["tor", "rpg", "random", "generators"]
license = "MIT"
version = "0.1.0"

[workspace.lints.rust]
future-incompatible = "warn"
keyword-idents = "warn"
let-underscore = "warn"
nonstandard-style = "warn"
refining-impl-trait = "warn"
rust-2018-idioms = "warn"
rust-2024-compatibility = "warn"
unused = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module-name-repetitions = "allow"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
