[package]
name = "loremaster"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
description = "Tools to help Loremasters running The One Ring 2E"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["tor", "rpg", "random", "generators"]
categories = ["games"]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0.75"
itertools = "0.12.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v2.0.1" }
strum = { version = "0.25.0", features = ["derive"] }

[lints.rust]
future_incompatible = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
nonstandard_style = "warn"
rust_2018_compatibility = "warn"
rust_2018_idioms = "warn"
rust_2021_compatibility = "warn"
unused = "warn"

[lints.clippy]
# cargo = "warn"
pedantic = "warn"

[workspace]
