spin_manifest_version = 2

[application]
name = "loremaster"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.brandt@aleph-alpha.com>"]
description = "Tools to help Loremasters running The One Ring 2E"

[[trigger.http]]
route = "/..."
component = "loremaster"

[component.loremaster]
source = "target/wasm32-wasip2/release/handler.wasm"
allowed_outbound_hosts = []
[component.loremaster.build]
command = "./build.sh"
watch = ["src/**/*.rs", "Cargo.toml"]
